/**
 * Admin API Endpoints
 * ===================
 * 
 * Admin-specific API functions with enhanced filtering,
 * bulk operations, and analytics.
 */

// Products
export {
  adminGetProducts,
  adminGetProduct,
  adminCreateProduct,
  adminUpdateProduct,
  adminDeleteProduct,
  adminBulkProductAction,
  adminToggleProductFeatured,
  adminToggleProductActive,
  adminGetProductAnalytics,
  adminImportProducts,
  adminExportProducts,
  adminCreateCategory,
  adminUpdateCategory,
  adminDeleteCategory,
  adminReorderCategories,
  type AdminProductFilters,
  type AdminProductListResponse,
  type AdminProduct,
  type ProductSummary,
  type BulkProductActionRequest,
  type BulkActionResponse,
  type ProductAnalytics,
  type ProductImportRequest,
  type ProductImportResponse,
} from './products';

// Orders
export {
  adminGetOrders,
  adminGetOrder,
  adminGetOrderByNumber,
  adminUpdateOrderStatus,
  adminAddShippingInfo,
  adminRefundOrder,
  adminCancelOrder,
  adminAddOrderNote,
  adminUpdateOrderAddress,
  adminBulkOrderAction,
  adminGetOrderAnalytics,
  adminGetOrdersRequiringAction,
  adminAddOrderFlag,
  adminRemoveOrderFlag,
  adminExportOrders,
  adminGetOrderStatusWorkflow,
  type AdminOrderFilters,
  type AdminOrderListResponse,
  type AdminOrder,
  type OrderSummary,
  type OrderTimelineEvent,
  type AdminNote,
  type OrderFlag,
  type RefundInfo,
  type BulkOrderActionRequest,
  type BulkOrderActionResponse,
  type AdminUpdateOrderStatusRequest,
  type RefundOrderRequest,
  type AddShippingInfoRequest,
  type OrderAnalytics,
} from './orders';

// Users
export {
  adminGetUsers,
  adminGetUser,
  adminGetUserByEmail,
  adminUpdateUser,
  adminUpdateUserStatus,
  adminSuspendUser,
  adminUnsuspendUser,
  adminBanUser,
  adminUnbanUser,
  adminDeleteUser,
  adminGetUserActivity,
  adminGetUserOrders,
  adminSendPasswordReset,
  adminVerifyEmail,
  adminSendVerificationEmail,
  adminAddUserFlag,
  adminRemoveUserFlag,
  adminBulkUserAction,
  adminExportUsers,
  adminImpersonateUser,
  adminGetUserStats,
  type UserStatus,
  type AdminUserFilters,
  type AdminUserListResponse,
  type AdminUser,
  type UserSummary,
  type UserFlag,
  type UserActivity,
  type AdminUpdateUserRequest,
  type BulkUserActionRequest,
} from './users';

// Vendors
export {
  adminGetVendors,
  adminGetVendor,
  adminUpdateVendor,
  adminActivateVendor,
  adminSuspendVendor,
  adminUnsuspendVendor,
  adminDeactivateVendor,
  adminVerifyVendor,
  adminGetVendorDocuments,
  adminReviewDocument,
  adminGetVendorPerformance,
  adminGetVendorPayouts,
  adminCreateVendorPayout,
  adminUpdateCommissionRate,
  adminAddVendorFlag,
  adminRemoveVendorFlag,
  adminBulkVendorAction,
  adminExportVendors,
  adminGetVendorStats,
  adminNotifyVendor,
  type VendorStatus,
  type VerificationStatus,
  type AdminVendorFilters,
  type AdminVendorListResponse,
  type AdminVendor,
  type VendorDocument,
  type VendorFlag,
  type VendorListSummary,
  type VendorPerformance,
  type VendorPayout,
  type AdminUpdateVendorRequest,
  type VendorVerificationRequest,
  type BulkVendorActionRequest,
  type BulkVendorActionResponse,
} from './vendors';

// Finance
export {
  adminGetFinancialSummary,
  adminGetRevenueData,
  adminGetTransactions,
  adminGetTransaction,
  adminGetPayouts,
  adminGetPayout,
  adminCreatePayout,
  adminProcessPayout,
  adminCancelPayout,
  adminRetryPayout,
  adminGetEscrowAccounts,
  adminGetEscrowAccount,
  adminReleaseEscrow,
  adminRefundEscrow,
  adminGetFinancialReports,
  adminGenerateReport,
  adminDownloadReport,
  adminGetCommissionSettings,
  adminUpdateCommissionSettings,
  type FinancialSummary,
  type RevenueDataPoint,
  type Transaction,
  type Payout,
  type EscrowAccount,
  type FinancialReport,
  type TransactionFilters,
  type PayoutFilters,
  type EscrowFilters,
  type CreatePayoutRequest,
  type ProcessPayoutRequest,
} from './finance';
